version: 0.2

phases:
  install:
    commands:
      - echo Installing npm dependencies
      - npm install -g vue-cli
      - echo Installed vue cli
      - npm install -g quasar-cli
      - echo installed quasar cli
    finally:
      - echo Install commands over      
  pre_build:
    commands:
      - echo Installing npm install
      - npm install      
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - quasar build -m pwa
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - dist/pwa-mat/*
    - appspec.yml
  discard-paths: yes
